AWSTemplateFormatVersion: '2010-09-09'

Description: Monitoring and alerting system for serverless API applications that use API Gateway and Lambda.

Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name

  LaunchConstraintRole:
    Type: String
    Description: Launch constraint role for Serverless Monitoring products.

  PortfolioId:
    Type: String
    Description: The SC portfolio this product will be attached to.

  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.

Resources:
  ServerlessMonitoringProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Serverless Monitoring
      Description: This product builds a SNS Topic for sending alarm notifications via email API Gateway CloudWatch Alarms4XX error alarm, client errors5XX error alarm, and server errors Lambda CloudWatch Alarm Monitors function execution errors.
      Owner: !Ref PortfolioProvider
      Distributor: !Ref PortfolioProvider
      SupportDescription: ITS Cloud Support
      SupportEmail: ITSCloudSupport@mathematica-mpr.com
      ProductType: CLOUD_FORMATION_TEMPLATE
      ProvisioningArtifactParameters:
        - Description: Serverless Monitoring solution 
          Info:
            LoadTemplateFromURL: !Sub '${RepoRootURL}serverless/sc-serverless-monitoring.yaml'
          Name: Serverless Monitoring v1.0

  AssociateServerlessMonitoringProduct:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref ServerlessMonitoringProduct

  constraintServerlessMonitoring:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: AssociateServerlessMonitoringProduct
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref ServerlessMonitoringProduct
      LocalRoleName: !Ref LaunchConstraintRole
      Description: !Ref LaunchConstraintRole

Outputs:
  ProductId:
    Value: !Ref ServerlessMonitoringProduct