AWSTemplateFormatVersion: '2010-09-09'

Description: EC2 Portfolio for Service Catalog. (fdp-1p4da46nc)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Portfolio Information
        Parameters:
          - PortfolioName
          - PortfolioProvider
          - PortfolioDescription
      - Label:
          default: IAM Settings
        Parameters:
          - LaunchRoleName
          - LinkedRole1
          - LinkedRole2
      - Label:
          default: Product Settings
        Parameters:
          - RepoRootURL

Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name
    Default: ITS Cloud Support

  PortfolioName:
    Type: String
    Description: Portfolio Name
    Default: MCSS Service Catalog EC2 Reference Architecture

  PortfolioDescription:
    Type: String
    Description: Portfolio Description
    Default: MCSS Service Catalog Portfolio that contains reference architecture products for Amazon Elastic Compute Cloud (EC2).
 
  LaunchRoleName:
    Type: String
    Description: Name of the launch constraint role for EC2 products. Leave this blank to create the role.
 
  LinkedRole1:
    Type: String
    Description: (Optional) The name of a role which can execute products in this portfolio.
    Default: 'AWSServiceCatalogAdminFullAccess'

  LinkedRole2:
    Type: String
    Description: (Optional) The name of a second role which can execute products in this portfolio.
    Default: 'AWSServiceCatalogEndUserAccess'

  LinkedRole3:
    Type: String
    Description: (Optional) The name of a third role which can execute products in this portfolio.
    Default: 'AdministratorAccess'

  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.
    Default: https://s3.amazonaws.com/aws-service-catalog-reference-architectures-314628052097/

Conditions:
  CreateLaunchConstraint: !Equals 
    - !Ref LaunchRoleName
    - ''
  CondLinkRole1: !Not 
    - !Equals 
      - !Ref LinkedRole1
      - ''
  CondLinkRole2: !Not 
    - !Equals 
      - !Ref LinkedRole2
      - ''

Resources:
  SCEC2portfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      ProviderName: !Ref PortfolioProvider
      Description: !Ref PortfolioDescription
      DisplayName: !Ref PortfolioName
 
  addrole1:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Condition: CondLinkRole1
    Properties:
      PrincipalARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${LinkedRole1}'
      PortfolioId: !Ref SCEC2portfolio
      PrincipalType: IAM
 
  addrole2:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Condition: CondLinkRole2
    Properties:
      PrincipalARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${LinkedRole2}'
      PortfolioId: !Ref SCEC2portfolio
      PrincipalType: IAM
 
  LaunchConstraintRole:
    Type: AWS::CloudFormation::Stack
    Condition: CreateLaunchConstraint
    Properties:
      TemplateURL: !Sub '${RepoRootURL}iam/sc-ec2vpc-launchrole.yml'
      TimeoutInMinutes: 5
 
  ec2linux2023product:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PortfolioProvider: !Ref PortfolioProvider
        LaunchConstraintRole: !If 
          - CreateLaunchConstraint
          - !GetAtt 
            - LaunchConstraintRole
            - Outputs.LaunchRoleName
          - !Ref LaunchRoleName
        PortfolioId: !Ref SCEC2portfolio
        RepoRootURL: !Ref RepoRootURL
      TemplateURL: !Sub '${RepoRootURL}ec2/sc-ec2-linux2023-instance.yaml'
      TimeoutInMinutes: 5
 
  ec2windows2016product:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PortfolioProvider: !Ref PortfolioProvider
        LaunchConstraintRole: !If 
          - CreateLaunchConstraint
          - !GetAtt 
            - LaunchConstraintRole
            - Outputs.LaunchRoleName
          - !Ref LaunchRoleName
        PortfolioId: !Ref SCEC2portfolio
        RepoRootURL: !Ref RepoRootURL
      TemplateURL: !Sub '${RepoRootURL}ec2/sc-ec2-windows2016-instance.yaml'
      TimeoutInMinutes: 5
 
  ec2windows2019product:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PortfolioProvider: !Ref PortfolioProvider
        LaunchConstraintRole: !If 
          - CreateLaunchConstraint
          - !GetAtt 
            - LaunchConstraintRole
            - Outputs.LaunchRoleName
          - !Ref LaunchRoleName
        PortfolioId: !Ref SCEC2portfolio
        RepoRootURL: !Ref RepoRootURL
      TemplateURL: !Sub '${RepoRootURL}ec2/sc-ec2-windows2019-instance.yaml'
      TimeoutInMinutes: 5
 
  ec2windows2022product:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PortfolioProvider: !Ref PortfolioProvider
        LaunchConstraintRole: !If 
          - CreateLaunchConstraint
          - !GetAtt 
            - LaunchConstraintRole
            - Outputs.LaunchRoleName
          - !Ref LaunchRoleName
        PortfolioId: !Ref SCEC2portfolio
        RepoRootURL: !Ref RepoRootURL
      TemplateURL: !Sub '${RepoRootURL}ec2/sc-ec2-windows2022-instance.yaml'
      TimeoutInMinutes: 5
 
Outputs:
  LaunchConstraintRoleARN:
    Condition: CreateLaunchConstraint
    Value: !GetAtt 
      - LaunchConstraintRole
      - Outputs.LaunchRoleArn
 
  LaunchConstraintRoleName:
    Condition: CreateLaunchConstraint
    Value: !GetAtt 
      - LaunchConstraintRole
      - Outputs.LaunchRoleName
 
  ec2linux2023productId:
    Value: !GetAtt 
      - ec2linux2023product
      - Outputs.ProductId

  ec2windows2022productId:
    Value: !GetAtt 
      - ec2windows2022product
      - Outputs.ProductId
 
  ec2windows2019productId:
    Value: !GetAtt 
      - ec2windows2019product
      - Outputs.ProductId
 
  ec2windows2016productId:
    Value: !GetAtt 
      - ec2windows2016product
      - Outputs.ProductId
