AWSTemplateFormatVersion: '2010-09-09'

Description: VPC endpoint Service Catalog product.

Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name

  LaunchConstraintRole:
    Type: String
    Description: Launch constraint role for VPC endpoint products.

  PortfolioId:
    Type: String
    Description: The SC portfolio this product will be attached to.

  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.

Resources:
  VPCEndpointProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: VPC Endpoint
      Description: This CloudFormation template creates and configures a VPC endpoint.
      Owner: !Ref PortfolioProvider
      Distributor: !Ref PortfolioProvider
      SupportDescription: ITS Cloud Support
      SupportEmail: ITSCloudSupport@mathematica-mpr.com
      ProductType: CLOUD_FORMATION_TEMPLATE
      ProvisioningArtifactParameters:
        - Description: VPC endpoint
          Info:
            LoadTemplateFromURL: !Sub "${RepoRootURL}vpc-endpoints/sc-template-vpcendpoints-createEndpoint.yaml"
          Name: VPC Endpoint v1.0

  AssociateVPCEndpointProduct:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref VPCEndpointProduct

  VPCEndpointLaunchConstraint:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: AssociateVPCEndpointProduct
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref VPCEndpointProduct
      LocalRoleName: !Ref LaunchConstraintRole
      Description: !Ref LaunchConstraintRole

Outputs:
  ProductId:
    Value: !Ref VPCEndpointProduct