Description: "ServiceCatalog EC2 and VPC Launch Role. (fdp-1p5rtpgmo)"
Resources:
  SCEC2LaunchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: SCEC2LaunchRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - servicecatalog.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: SCLaunchPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: SCLaunchPolicySID
                Effect: Allow
                Action:
                  - "cloudformation:CreateStack"
                  - "cloudformation:DeleteStack"
                  - "cloudformation:DescribeStackEvents"
                  - "cloudformation:DescribeStackEvents"
                  - "cloudformation:DescribeStackResource"
                  - "cloudformation:DescribeStackResources"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:GetTemplate"
                  - "cloudformation:GetTemplateSummary"
                  - "cloudformation:List*"
                  - "cloudformation:SetStackPolicy"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:ValidateTemplate"
                  - "iam:AddRoleToInstanceProfile"
                  - "iam:AttachRolePolicy"
                  - "iam:CreateInstanceProfile"
                  - "iam:CreateRole"
                  - "iam:DeleteInstanceProfile"
                  - "iam:DeleteRole"
                  - "iam:DeleteRolePolicy"
                  - "iam:DetachRolePolicy"
                  - "iam:GetInstanceProfile"
                  - "iam:GetRole"
                  - "iam:ListInstanceProfiles"
                  - "iam:ListInstanceProfilesForRole"
                  - "iam:ListPolicies"
                  - "iam:ListRolePolicies"
                  - "iam:ListRoles"
                  - "iam:PassRole"
                  - "iam:PutRolePolicy"
                  - "iam:RemoveRoleFromInstanceProfile"
                  - "iam:TagRole" 
                  - "iam:TagUser"
                  - "iam:UntagRole"
                  - "iam:UntagUser"
                  - "iam:getRolePolicy"
                  - "s3:GetObject"
                  - "servicecatalog:AssociateResource"
                  - "servicecatalog:DisassociateResource"
                  - "servicecatalog:ExecuteprovisionedProductServiceAction"
                  - "servicecatalog:ListServiceActionsForProvisioningArtifact"
                Resource: '*'
        - PolicyName: CloudWatchPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudWatchPolicySID
                Effect: Allow
                Action:
                  - "cloudwatch:PutMetricAlarm"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:TagResource"
                  - "logs:CreateLogGroup"
                  - "logs:DescribeLogGroups"
                  - "logs:TagLogGroup"
                  - "logs:PutRetentionPolicy"
                Resource: '*'
Outputs:
    LaunchRoleArn:
        Value: !GetAtt SCEC2LaunchRole.Arn
    LaunchRoleName:
        Value: !Ref SCEC2LaunchRole
        