AWSTemplateFormatVersion: '2010-09-09'
Description: "ServiceCatalog Serverless Launch Role. (fdp-1p5s1035k)"
Resources:
  SCServerlessLaunchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: SCServerlessLaunchRole 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - servicecatalog.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: SCLaunchPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: SCLaunchPolicySID
                Effect: "Allow"
                Action:
                  - "cloudformation:CancelUpdateStack"
                  - "cloudformation:ContinueUpdateRollback"
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:CreateStack"
                  - "cloudformation:DeleteStack"
                  - "cloudformation:Describe*"
                  - "cloudformation:ExecuteChangeSet"
                  - "cloudformation:Get*"
                  - "cloudformation:List*"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:UpdateTerminationProtection"
                  - "cloudformation:ValidateTemplate"
                  - "cloudwatch:DeleteAlarms"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:PutMetricAlarm"
                  - "sns:CreateTopic"
                  - "sns:DeleteTopic"
                  - "sns:GetTopicAttributes"
                  - "sns:ListSubscriptionsByTopic"
                  - "sns:ListTopics"
                  - "sns:SetTopicAttributes"
                  - "sns:Subscribe"
                  - "sns:Unsubscribe"
                Resource: '*'
                
Outputs:
    LaunchRoleArn:
        Value: !GetAtt SCServerlessLaunchRole.Arn
    LaunchRoleName:
        Value: !Ref SCServerlessLaunchRole
        