AWSTemplateFormatVersion: '2010-09-09'

Description: "AWS Service Catalog VPC Endpoints launch constraint role."

Resources:
  SCVPCEndpointsLaunchConstraintRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SCVPCEndpointsLaunchConstraintRole
      Description: >
        Launch role assumed by AWS Service Catalog to provision
        CloudFormation-based Service Catalog products.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowServiceCatalogAssumeRole
            Effect: Allow
            Principal:
              Service:
                - servicecatalog.amazonaws.com
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
              ArnLike:
                aws:SourceArn: !Sub
                  arn:${AWS::Partition}:servicecatalog:${AWS::Region}:${AWS::AccountId}:*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      Policies:
        - PolicyName: ServiceCatalogProvisioningArtifactAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ReadServiceCatalogProvisioningArtifacts
                Effect: Allow
                Action:
                  - s3:GetObject
                Resource: '*'
                Condition:
                  StringEquals:
                    s3:ExistingObjectTag/servicecatalog:provisioning: 'true'
        - PolicyName: ProductResourcePermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowResourceTagging
                Effect: Allow
                Action:
                  - tag:GetResources
                  - tag:TagResources
                  - tag:UntagResources
                Resource: '*'
              - Sid: ProductServicePermissions
                Effect: Allow
                Action:
                  - ec2:Describe*
                  - ec2:CreateVpcEndpoint
                  - ec2:ModifyVpcEndpoint
                  - ec2:DeleteVpcEndpoints
                  - ec2:CreateSecurityGroup
                  - ec2:DeleteSecurityGroup
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:CreateTags
                  - ec2:DeleteTags
                Resource: '*'

Outputs:
  LaunchRoleName:
    Description: IAM role name to use for the Service Catalog launch constraint.
    Value: !Ref SCVPCEndpointsLaunchConstraintRole
  LaunchRoleArn:
    Description: IAM role ARN to use for the Service Catalog launch constraint.
    Value: !GetAtt SCVPCEndpointsLaunchConstraintRole.Arn