AWSTemplateFormatVersion: '2010-09-09'

Description: "AWS Service Catalog VPC launch constraint role."

Resources:
  SCVPCLaunchConstraintRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: SCVPCLaunchConstraintRole
      Description: >
        Launch role assumed by AWS Service Catalog to provision
        CloudFormation-based Service Catalog products.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowServiceCatalogAssumeRole
            Effect: Allow
            Principal:
              Service:
                - servicecatalog.amazonaws.com
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
              ArnLike:
                aws:SourceArn: !Sub
                  arn:${AWS::Partition}:servicecatalog:${AWS::Region}:${AWS::AccountId}:*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      Policies:
        - PolicyName: ServiceCatalogProvisioningArtifactAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ReadServiceCatalogProvisioningArtifacts
                Effect: Allow
                Action:
                  - s3:GetObject
                Resource: '*'
                Condition:
                  StringEquals:
                    s3:ExistingObjectTag/servicecatalog:provisioning: 'true'
        - PolicyName: ProductResourcePermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowResourceTagging
                Effect: Allow
                Action:
                  - tag:GetResources
                  - tag:TagResources
                  - tag:UntagResources
                Resource: '*'
              - Sid: ProductServicePermissions
                Effect: Allow
                Action:
                  - "ec2:*"
                  - "elasticloadbalancing:*"
                  - "cloudwatch:*"
                  - "autoscaling:*"
                Resource: '*'

Outputs:
    LaunchRoleArn:
        Value: !GetAtt SCVPCLaunchConstraintRole.Arn
    LaunchRoleName:
        Value: !Ref SCVPCLaunchConstraintRole
        