AWSTemplateFormatVersion: '2010-09-09'

Description: Sets up common tasks for GitHub Actions workflows, including necessary IAM roles and policies.

Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name

  LaunchConstraintRole:
    Type: String
    Description: Launch constraint role for Common Tasks - GitHub Actions Setup product.

  PortfolioId:
    Type: String
    Description: The SC portfolio this product will be attached to.

  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.

Resources:
  CommonTasksProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Common Tasks - GitHub Actions Setup
      Description: This product sets up common tasks for GitHub Actions workflows, including necessary IAM roles and policies.
      Owner: !Ref PortfolioProvider
      Distributor: !Ref PortfolioProvider
      SupportDescription: ITS Cloud Support
      SupportEmail: ITSCloudSupport@mathematica-mpr.com
      ProductType: CLOUD_FORMATION_TEMPLATE
      ProvisioningArtifactParameters:
        - Description: Common Tasks - GitHub Actions Setup v1.0
          Info:
            LoadTemplateFromURL: !Sub '${RepoRootURL}common-tasks/sc-template-common-tasks-github-actions-setup.yaml'
          Name: Common Tasks - GitHub Actions Setup v1.0

  AssociateCommonTasksProduct:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref CommonTasksProduct

  constraintCommonTasks:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: AssociateCommonTasksProduct
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref CommonTasksProduct
      LocalRoleName: !Ref LaunchConstraintRole
      Description: !Ref LaunchConstraintRole

Outputs:
  ProductId:
    Value: !Ref CommonTasksProduct