AWSTemplateFormatVersion: '2010-09-09'

Description: ELB product for encrypted port forwarding.

Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name

  LaunchConstraintRole:
    Type: String
    Description: Launch constraint role for ELB products.

  PortfolioId:
    Type: String
    Description: The SC portfolio this product will be attached to.

  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.

Resources:
  ELBEncryptedPortFwdProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: ELB Encrypted Port Forwarding
      Description: This product sets up an ELB with encrypted port forwarding.
      Owner: !Ref PortfolioProvider
      Distributor: !Ref PortfolioProvider
      SupportDescription: ITS Cloud Support
      SupportEmail: ITSCloudSupport@mathematica-mpr.com
      ProductType: CLOUD_FORMATION_TEMPLATE
      ProvisioningArtifactParameters:
        - Description: ELB Encrypted Port Forwarding solution
          Info:
            LoadTemplateFromURL: !Sub '${RepoRootURL}elb/sc-elb-encrypted-port-fwd.yaml'
          Name: ELB Encrypted Port Forwarding v1.0

  AssociateELBEncryptedPortFwdProduct:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref ELBEncryptedPortFwdProduct

  constraintELBEncryptedPortFwd:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: AssociateELBEncryptedPortFwdProduct
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref ELBEncryptedPortFwdProduct
      LocalRoleName: !Ref LaunchConstraintRole
      Description: !Ref LaunchConstraintRole

Outputs:
  ProductId:
    Value: !Ref ELBEncryptedPortFwdProduct